
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: alunoonline
      MYSQL_PASSWORD: alunoonline
      MYSQL_ROOT_PASSWORD: alunoonline
      MYSQL_USER: alunoonline
    volumes:
      - alunoonline:/var/lib/mysql
    ports:
      - 3307:3306
volumes:
  alunoonline: