### Send POST request with json body
POST {{endtpoint}}/aluno
Content-Type: application/json

{
  "nome": "teste2",
  "email": ""
}

### Get all Alunos
GET  {{endtpoint}}/aluno/all
Content-Type: application/json


### Get Aluno
GET  {{endtpoint}}/aluno/3
Content-Type: application/json

